# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package #name of workflow

on:
  push:
    branches: [master] #when a new push happens on master branch trigger the workflow

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4 #fetches src code of repo in the environment
      - name: Use nodejs ${{matrix.node-version}}
      - uses: actions/setup-node@v4 #set up nodejs on the machine
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: pm2 restart backendserver

  
